const HELP_GROUP = 'help';
const BASIC_GROUP = 'basic';

const groups = {
    HELP_GROUP,
    BASIC_GROUP,
};
const commands = [];

const flags = [
    {
        name: 'config',
        usage: '--config <path to json-trim configuration file>',
        alias: 'c',
        type: String,
        description: 'Provide path to a json-trim configuration file e.g. ./conf/trim.config.js',
        link: 'https://github.com/auturge/json-trim/readme.md#ConfigurationFiles/',
    },
    {
        name: 'source',
        usage: '--source <path to target file>',
        alias: 's',
        type: String,
        multiple: false,
        description: 'Input location of the file json-trim should copy, e.g., ./package.json',
        link: 'https://github.com/auturge/json-trim/readme.md#source/',
    },
    {
        name: 'destination',
        usage: '--destination <path to target file>',
        alias: 'd',
        type: String,
        multiple: false,
        description: 'Output location of the file generated by json-trim, e.g., ./build/dev/package.json',
        link: 'https://github.com/auturge/json-trim/readme.md#destination/',
    },
    {
        name: 'keeplist',
        usage: '--keeplist <list> <of> <keys>',
        alias: 'k',
        type: String,
        multiple: true,
        description: 'List of json keys to copy, e.g., name version description',
        // link: 'https://github.com/auturge/json-trim/readme.md#target/',
    },
    {
        name: 'trimlist',
        usage: '--trimlist <list> <of> <keys>',
        alias: 't',
        type: String,
        multiple: true,
        description: 'List of json keys to exclude (takes precedence over keeplist)',
        // link: 'https://github.com/auturge/json-trim/readme.md#target/',
    },
    {
        name: 'env',
        usage: '--env <environment>',
        type: String,
        multipleType: true,
        description: 'Environment passed to the configuration when it is a function',
    },
    {
        name: 'help',
        usage: '--help',
        alias: "-help",
        type: Boolean,
        group: HELP_GROUP,
        description: 'Displays usage information',
    },
    {
        name: 'quiet',
        usage: '--quiet',
        alias: "q",
        type: Boolean,
        group: HELP_GROUP,
        description: 'Toggles quiet mode. Will only output errors',
    },
    {
        name: 'quiet',
        usage: '--no-quiet',
        negative: true,
        type: Boolean,
        group: HELP_GROUP,
        description: 'Toggles quiet mode. Will only output errors',
    },
    {
        name: 'verbose',
        usage: '--verbose',
        alias: "v",
        type: Boolean,
        group: HELP_GROUP,
        description: 'Toggles verbose mode',
    },
    {
        name: 'version',
        usage: '--version',
        alias: "ver",
        type: Boolean,
        group: HELP_GROUP,
        description: 'Displays the current version',
    }
];

module.exports = {
    groups,
    commands,
    flags: flags
};
